/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  2412                                  |
|   \\  /    A nd           | Website:  www.openfoam.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : _b8cf4d35-20260127 OPENFOAM=2412 patch=260127 version=2412
Arch   : "LSB;label=32;scalar=64"
Exec   : soPlasmaFoam
Date   : Aug 13 2026
Time   : 20:42:40
Host   : Kourtzanidis-PC
PID    : 1233097
I/O    : uncollated
Case   : /home/kkourtza/soplasma-scratch/src/models/plasmaModels/plasmaTransport
nProcs : 1
trapFpe: Floating point exception trapping enabled (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 5, maxFileModificationPolls 20)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time



--> FOAM FATAL ERROR: (openfoam-2412 patch=260127)
cannot find file "/home/kkourtza/soplasma-scratch/src/models/plasmaModels/plasmaTransport/system/controlDict"

    From virtual Foam::autoPtr<Foam::ISstream> Foam::fileOperations::uncollatedFileOperation::readStream(Foam::regIOobject&, const Foam::fileName&, const Foam::word&, bool) const
    in file global/fileOperations/uncollatedFileOperation/uncollatedFileOperation.C at line 629.

FOAM exiting

