/*---------------------------------------------------------------------------*\
License
    This file is part of SoPLASMA.

    Copyright (C) 2026

    This program is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation, either version 3 of the License, or (at your
    option) any later version.

Application
    testChemistryBackends

Description
    Cross-validation of the two heavy-chemistry backends, native and Cantera,
    on the identical mechanism.

    The point of the test is that there is nothing to calibrate: both backends
    are handed the same reactions, generated by mechc from one master file, so
    they must return the same dn/dt at the same state. Any disagreement is a
    units, stoichiometry or third-body error in one of the two paths -- every
    class of bug this coupling has actually produced.

    Two comparisons, because they fail differently:

      RATES     net dn/dt per species over a sweep of states spanning nine
                decades of ionisation fraction. Catches a constant factor
                immediately and localises it to a species.

      0-D       both backends integrated over the same interval from the same
                initial condition. Catches an error that cancels in the
                instantaneous rate but accumulates -- and is the quantity a
                simulation actually depends on.

    Runs WITHOUT a mesh: the chemistry is a per-cell object and needs only the
    mechanism dictionary, so this costs a second rather than a meshing run.

Usage
    testChemistryBackends [-mechanism <file>] [-Tgas 300] [-dt 1e-9]

\*---------------------------------------------------------------------------*/

#include "argList.H"
#include "Time.H"
#include "IFstream.H"
#include "OFstream.H"
#include "plasmaChemistry.H"

using namespace Foam;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

int main(int argc, char *argv[])
{
    argList::noParallel();
    argList::addOption("mechanism", "file", "mechanism dictionary (.foam)");
    argList::addOption("Tgas", "K", "gas temperature [K] (default 300)");
    argList::addOption("dt", "s", "0-D integration interval [s] (default 1e-9)");
    argList::addOption("out", "file", "CSV output (default backends.csv)");
    argList::addOption("canteraJacobian", "auto|finiteDifference",
                       "heavy Jacobian source (default auto)");

    #include "setRootCase.H"
    #include "createTime.H"

    const fileName mechFile
    (
        args.getOrDefault<fileName>("mechanism", "constant/air_plasma.foam")
    );
    const scalar Tgas = args.getOrDefault<scalar>("Tgas", 300.0);
    const scalar dt   = args.getOrDefault<scalar>("dt", 1e-9);
    const fileName outFile
    (
        args.getOrDefault<fileName>("out", "backends.csv")
    );

    // ---- species and charges straight from the mechanism --------------------
    // Exactly as `activeSpecies fromMechanism` does in a case, so the test
    // exercises the same species set and the same ordering the solver sees.
    IFstream is(mechFile);
    if (!is.good())
    {
        FatalErrorInFunction
            << "Cannot open " << mechFile << nl << exit(FatalError);
    }
    const dictionary mech(is);
    const dictionary& qDict = mech.subDict("speciesCharge");

    wordList species(qDict.toc());
    scalarField charge(species.size(), Zero);
    forAll(species, i) charge[i] = qDict.get<scalar>(species[i]);

    const scalar nGas = 2.446e25;   // 1 bar, 300 K

    Info<< "Mechanism  : " << mechFile << nl
        << "Species    : " << species.size() << nl
        << "Tgas       : " << Tgas << " K" << nl
        << "Background : " << nGas << " m^-3" << nl << endl;

    // ---- the two backends ---------------------------------------------------
    // The electron's name comes from the mechanism, not from a guess: the
    // species list here IS the mechanism's, so the two names coincide. An
    // earlier version inferred it from charge and name length and selected
    // `Om`, which silently redirected every electron reaction onto O- and
    // produced exactly the kind of backend disagreement this test hunts for.
    dictionary cfg;
    cfg.add("electronName", mech.getOrDefault<word>("electronSpecies", "Electron"));
    cfg.add("backgroundDensity", nGas);
    cfg.add("Tgas", Tgas);

    dictionary nCfg(cfg); nCfg.add("chemistryBackend", word("native"));
    dictionary cCfg(cfg); cCfg.add("chemistryBackend", word("cantera"));
    cCfg.add("canteraJacobian",
             args.getOrDefault<word>("canteraJacobian", "auto"));

    Info<< "--- native ---" << endl;
    plasmaChemistry nat(mechFile, species, charge, nCfg);
    Info<< "--- cantera ---" << endl;
    plasmaChemistry can(mechFile, species, charge, cCfg);

    // Electron-impact rates are tabulated and identical by construction on
    // both paths, so they are set to zero: this test isolates the HEAVY
    // chemistry, which is the only thing the two backends compute differently.
    scalarField kTab(max(nat.nTabulated(), 1), Zero);

    // ---- 1. instantaneous rates over a sweep of states -----------------------
    OFstream os(outFile);
    os << "# native vs Cantera heavy chemistry, mechanism " << mechFile << nl
       << "# Tgas = " << Tgas << " K, background = " << nGas << " m^-3" << nl
       << "# electron-impact rates set to zero: heavy chemistry only" << nl
       << "ionFrac,species,dndt_native,dndt_cantera,relDiff" << nl;

    scalar worstRate = 0.0;
    word   worstSp;
    scalar worstFrac = 0.0;

    for (label e = 0; e <= 9; ++e)
    {
        const scalar frac = Foam::pow(10.0, -12.0 + scalar(e));

        scalarField n(species.size(), Zero);
        forAll(n, i) n[i] = frac*nGas;

        scalarField dnN(species.size(), Zero), dnC(species.size(), Zero);
        nat.derivatives(n, kTab, Tgas, dnN);
        can.derivatives(n, kTab, Tgas, dnC);

        // Measured PER SPECIES, against that species' own rate. An earlier
        // version scaled every species on the largest rate in the state, and a
        // factor-of-2.2 error on a slow channel came out as 1e-8 -- a bug that
        // an eye scanning for round numbers would pass over. The global scale
        // is kept only as a floor, to stop species whose rate is genuine
        // roundoff from reporting a large relative error on noise.
        scalar scale = 0.0;
        forAll(dnN, i) scale = max(scale, mag(dnN[i]));

        forAll(species, i)
        {
            const scalar den = max(mag(dnN[i]), 1e-14*scale);
            const scalar rel = (den > VSMALL) ? mag(dnN[i] - dnC[i])/den : 0.0;

            os  << frac << ',' << species[i] << ','
                << dnN[i] << ',' << dnC[i] << ',' << rel << nl;

            if (rel > worstRate)
            {
                worstRate = rel;
                worstSp   = species[i];
                worstFrac = frac;
            }
        }
    }

    // ---- 1b. Jacobians ------------------------------------------------------
    // The Jacobian is what makes `chemistrySolver ode` and `adaptive` usable
    // with Cantera at all. A Rosenbrock method is not Newton-iterated, so an
    // inexact Jacobian costs temporal ORDER rather than convergence rate --
    // it cannot be checked by watching a residual, and has to be checked here.
    //
    // Two comparisons: the two backends against each other, and Cantera's
    // analytic derivative against a finite difference of its own rates. The
    // second catches an error the first cannot -- both backends agreeing on a
    // wrong derivative -- because it never leaves Cantera.
    {
        const scalar frac = 1e-6;
        scalarField n(species.size(), Zero);
        forAll(n, i) n[i] = frac*nGas;

        scalarSquareMatrix Jn(species.size(), Zero), Jc(species.size(), Zero);
        scalarField dfdx(species.size(), Zero);
        nat.jacobian(n, kTab, Tgas, dfdx, Jn);
        can.jacobian(n, kTab, Tgas, dfdx, Jc);

        // Scaled per COLUMN: column j has the units of 1/time for every row,
        // so entries within a column are comparable while entries across
        // columns differ by the density ratio of species j to species i.
        scalar worstJ = 0.0;
        label wi = 0, wj = 0;
        for (label j = 0; j < species.size(); ++j)
        {
            scalar colScale = 0.0;
            for (label i = 0; i < species.size(); ++i)
            {
                colScale = max(colScale, mag(Jn(i, j)));
            }
            if (colScale <= VSMALL) continue;

            for (label i = 0; i < species.size(); ++i)
            {
                const scalar rel = mag(Jn(i, j) - Jc(i, j))/colScale;
                if (rel > worstJ) { worstJ = rel; wi = i; wj = j; }
            }
        }

        // Cantera's analytic derivative against a finite difference of the
        // Cantera rates themselves. One-sided, so ~1e-6 relative is the
        // expected agreement -- this is a correctness check, not a precision
        // one, and it fails by orders of magnitude when it fails.
        scalar worstFD = 0.0;
        label fi = 0, fj = 0;
        scalarField P0, L0, Pp, Lp;
        can.productionLoss(n, kTab, Tgas, P0, L0);

        for (label j = 0; j < species.size(); ++j)
        {
            scalarField np(n);
            const scalar h = 1e-6*n[j];
            np[j] = n[j] + h;
            can.productionLoss(np, kTab, Tgas, Pp, Lp);

            scalar colScale = 0.0, fMax = 0.0;
            for (label i = 0; i < species.size(); ++i)
            {
                colScale = max(colScale, mag(Jc(i, j)));
                fMax = max(fMax, mag(P0[i] - L0[i]*n[i]));
            }
            if (colScale <= VSMALL) continue;

            // A difference quotient of two rates of size fMax carries roundoff
            // of order 2*eps*fMax/h -- here 5e-4, against a column scale of
            // 5e-3. For an entry whose true derivative is zero, which is most
            // of a sparse Jacobian, that noise is ALL the quotient contains:
            // d(N2+)/d(O2(a1)) came out as 3.5e-4 from a species pair that
            // shares no reaction, and reporting it as a 7% error was a
            // statement about double precision, not about the Jacobian.
            //
            // So the noise is SUBTRACTED before scaling, rather than used as a
            // denominator floor: a difference the quotient cannot resolve is
            // not evidence of anything.
            const scalar noise = 2.0*2.22e-16*fMax/h;

            for (label i = 0; i < species.size(); ++i)
            {
                const scalar fp = Pp[i] - Lp[i]*np[i];
                const scalar f0 = P0[i] - L0[i]*n[i];
                const scalar fd = (fp - f0)/h;
                const scalar rel =
                    max(mag(fd - Jc(i, j)) - noise, scalar(0))/colScale;
                if (rel > worstFD) { worstFD = rel; fi = i; fj = j; }
            }
        }

        Info<< nl << "Jacobian at ionFrac " << frac << ':' << nl
            << "    native vs Cantera        : " << worstJ
            << "  (d " << species[wi] << " / d " << species[wj] << ')' << nl
            << "    Cantera analytic vs FD   : " << worstFD
            << "  (d " << species[fi] << " / d " << species[fj] << ')' << nl;

        os << "# Jacobian check at ionFrac " << frac << nl
           << "check,worstRelDiff" << nl
           << "native_vs_cantera," << worstJ << nl
           << "cantera_analytic_vs_fd," << worstFD << nl;

        // The tolerance depends on which path supplied the Jacobian, because
        // the two are different claims. The analytic derivative should equal
        // the native one to roundoff -- they differentiate the same Arrhenius
        // expressions. The fallback IS a difference quotient, so it is held to
        // difference-quotient accuracy and nothing better.
        const bool analytic = can.canteraAnalyticJacobian();
        const scalar tolJ = analytic ? 1e-10 : 1e-2;

        Info<< "    (Jacobian source: "
            << (analytic ? "Cantera analytic" : "finite difference")
            << ", tolerance " << tolJ << ')' << nl;

        if (worstJ > tolJ || worstFD > 1e-4)
        {
            Info<< "*** JACOBIAN DISAGREEMENT ***" << nl;
            return 1;
        }
    }

    // ---- 2. 0-D integration -------------------------------------------------
    scalarField n0(species.size(), Zero);
    forAll(n0, i) n0[i] = 1e-6*nGas;

    scalarField nN(n0), nC(n0);
    nat.integrate(nN, kTab, Tgas, dt);
    can.integrate(nC, kTab, Tgas, dt);

    scalar worstInt = 0.0;
    word   worstIntSp;
    // Per species again, against that species' own CHANGE over the interval:
    // the densities themselves barely move in 1 ns, so comparing them directly
    // would divide a real discrepancy by a number a million times larger.
    scalar nScale = 0.0;
    forAll(nN, i) nScale = max(nScale, mag(nN[i] - n0[i]));

    Info<< nl << "0-D integration over " << dt << " s from n = 1e-6*nGas:" << nl
        << "    species        native            cantera           rel.diff"
        << nl;
    forAll(species, i)
    {
        const scalar den = max(mag(nN[i] - n0[i]), 1e-14*nScale);
        const scalar rel = (den > VSMALL) ? mag(nN[i] - nC[i])/den : 0.0;

        Info<< "    " << species[i].c_str() << "\t" << nN[i]
            << "\t" << nC[i] << "\t" << rel << nl;

        if (rel > worstInt) { worstInt = rel; worstIntSp = species[i]; }
    }

    os << "# 0-D integration, dt = " << dt << " s" << nl
       << "species,n_native,n_cantera,relDiff" << nl;
    forAll(species, i)
    {
        const scalar den = max(mag(nN[i] - n0[i]), 1e-14*nScale);
        const scalar rel = (den > VSMALL) ? mag(nN[i] - nC[i])/den : 0.0;
        os << species[i] << ',' << nN[i] << ',' << nC[i] << ',' << rel << nl;
    }

    // ---- verdict ------------------------------------------------------------
    Info<< nl
        << "worst instantaneous-rate difference : " << worstRate
        << "  (" << worstSp << " at ionFrac " << worstFrac << ")" << nl
        << "worst 0-D integrated difference     : " << worstInt
        << "  (" << worstIntSp << ')' << nl
        << "startup cross-check reported        : " << can.backendMismatch()
        << nl << nl
        << "written " << outFile << nl << endl;

    // 1e-10 is far above double roundoff and far below any real discrepancy:
    // the two backends evaluate the same Arrhenius expressions in a different
    // order, so they agree to summation order, not bit for bit.
    const scalar tol = 1e-10;
    if (max(worstRate, worstInt) > tol)
    {
        Info<< "*** DISAGREEMENT above " << tol << " ***" << nl
            << "    The two backends were given the same reactions, so this is"
            << " a defect in one of them -- units, stoichiometry or a third"
            << " body -- unless the mechanism uses reaction forms the native"
            << " parser cannot represent." << endl;
        return 1;
    }

    Info<< "Backends agree." << endl;
    Info<< "End\n" << endl;
    return 0;
}


// ************************************************************************* //
