#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase -noZero

rm -rf 0
rm -r constant/polyMesh
rm system/fvSolution
rm -rf logs

rm -r processor*



